# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c42a75ba5040be7728f72edd98cb1fa52d2e9565a38797036e9a0bac0ce3e3f1d36dde6eb614e324103c89d78f8bdc5f0723d177353bafb85c7977d8332d041

test:
  secret_key_base: d3394d4ae5a611b1b7179624f90e7a1980fe87d44511bfe3e496f9cc6b296bc94d688baf629a09a926cbcf51bb6f3d2f9f2d7135037352dec9249783ad20d84b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
